spring:
  datasource:
    url: jdbc:mysql://${MYSQL_DATABASE_URL:localhost}:${MYSQL_PORT:3309}/hentori
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:admin123}
  session:
    store-type: redis
  data:
    redis:
      port: 16379
      host: localhost
      password: admin123
---
mycustom:
  email:
    receiver: hentorij@gmail.com
    root: nguyenthanhsang60309@gmail.com
    password: kvyzxyljmfywprpv